FROM containers.global.prod.stripe.io/stripe/build/ubuntu-20.04:latest

# Since we set post_build: true in stripe-build.yaml, this Dockerfile
# ends up running in the /build/ folder (which is where the Jenkins
# build copies the DataHub tarballs). We use the generated
# artifacts to build our container image.

RUN mkdir -p /datahub
COPY datahub-frontend.zip /datahub
RUN cd /datahub && unzip datahub-frontend.zip && rm datahub-frontend.zip

# create logs dir and update perms to allow the DataHub process to be able to write
# to it (runs as a different user)
RUN mkdir -p /datahub/datahub-frontend/logs
RUN mkdir -p /datahub/datahub-gms/logs
RUN chmod 777 /datahub/datahub-frontend/logs
RUN chmod 777 /datahub/datahub-gms/logs

RUN mkdir -p /datahub/datahub-mxe-consumers/logs
RUN chmod 777 /datahub/datahub-mxe-consumers/logs

# Set up things for metadata service
RUN mkdir -p /datahub/datahub-gms/resources
RUN mkdir -p /datahub/datahub-gms/scripts
RUN mkdir -p /datahub/datahub-gms/bin

RUN mkdir -p /datahub/datahub-mxe-consumers/resources
RUN mkdir -p /datahub/datahub-mxe-consumers/scripts
RUN mkdir -p /datahub/datahub-mxe-consumers/bin

COPY entity-registry.yml /datahub/datahub-gms/resources/entity-registry.yml
COPY stripe-jmxfetch.yaml /datahub/datahub-gms/resources/stripe-jmxfetch.yaml
COPY war.war /datahub/datahub-gms/bin/war.war
COPY jetty.xml /datahub/datahub-gms/scripts/jetty.xml
COPY stripe-start.sh /datahub/datahub-gms/scripts/stripe-start.sh
COPY mysql_init.sh /datahub/datahub-gms/scripts/stripe-init.sh
COPY mysql_init.sql /datahub/datahub-gms/scripts/init.sql
COPY stripe-frontend-start.sh /datahub/datahub-frontend/bin/stripe-frontend-start.sh
COPY jetty-runner.jar /datahub/datahub-gms/bin/jetty-runner.jar
COPY jetty-util.jar /datahub/datahub-gms/bin/jetty-util.jar
COPY jetty-jmx.jar /datahub/datahub-gms/bin/jetty-jmx.jar
# enable analytics
COPY create-indices.sh /datahub/datahub-gms/scripts/create-indices.sh
COPY policy.json /datahub/datahub-gms/resources/policy.json
COPY index_template.json /datahub/datahub-gms/resources/index_template.json

COPY entity-registry.yml /datahub/datahub-mxe-consumers/resources/entity-registry.yml
COPY mce-stripe-jmxfetch.yaml /datahub/datahub-mxe-consumers/resources/mce-stripe-jmxfetch.yaml
COPY mae-stripe-jmxfetch.yaml /datahub/datahub-mxe-consumers/resources/mae-stripe-jmxfetch.yaml
COPY mxe-stripe-start.sh /datahub/datahub-mxe-consumers/scripts/mxe-stripe-start.sh
COPY mce-consumer-job.jar /datahub/datahub-mxe-consumers/bin/mce-consumer-job.jar
COPY mae-consumer-job.jar /datahub/datahub-mxe-consumers/bin/mae-consumer-job.jar

# install mysql-client to help with MySQL init
RUN apt-get update && apt-get install -y mysql-client

WORKDIR /datahub
